name: blog_repository
description: A repository to my local
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  dio: ^4.0.4
  retrofit: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  retrofit_generator: ^3.0.1
  mocktail: ^0.2.0

flutter:
